project_id = "wexytifqxnbjflsnpvlx"

[functions.notify-event-moderation]
verify_jwt = true

[functions.moderate-event]
verify_jwt = true

[functions.send-feedback]
verify_jwt = false

[functions.ingest-resend-email]
verify_jwt = false

